version: "3.8"
services: 
  app: 
    build: .
    volumes: 
      - .:/django
    ports:
      - 8000:8000
    image: r1cht3rphil/app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080